# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.0
info:
  description: Druid Api Documentation
  version: 2.0.0
  title: Druid Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: /server
  - name: /router
servers:
  - url: /

# Server API

paths:
  /status:
    get:
      tags:
        - /server
        - /router
      summary: getServerStatus
      operationId: getServerStatus
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerStatus'
              example:
                $ref: /examples/get-server-status.json

        401:
          description: Unauthorized
        403:
          description: Forbidden

# Router API

  /druid/v2/datasources:
    get:
      tags:
        - /router
      summary: getDataSourcesNames
      operationId: getDataSourcesNames
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                $ref: /examples/get-data-sources-names.json

        401:
          description: Unauthorized
        403:
          description: Forbidden
  /druid/v2/datasources/{dataSourceName}:
    get:
      tags:
        - /router
      summary: getDataSource
      operationId: getDataSource
      parameters:
        - name: dataSourceName
          in: path
          description: dataSourceName
          required: true
          schema:
            type: string
        - name: interval
          in: query
          required: false
          schema:
            type: string
            example: 2020-01-01/2020-06-30
        - name: full
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSource'
              example:
                $ref: /examples/get-data-source.json
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /druid/v2/datasources/{dataSourceName}/dimensions:
    get:
      tags:
        - /router
      summary: getDataSourceDimensions
      operationId: getDataSourceDimensions
      deprecated: true
      parameters:
        - name: dataSourceName
          in: path
          description: dataSourceName
          required: true
          schema:
            type: string
        - name: interval
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSourceDimention'
              example:
                $ref: /examples/get-data-source-dimensions.json
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /druid/v2/datasources/{dataSourceName}/metrics:
    get:
      tags:
        - /router
      summary: getDataSourceMetrics
      operationId: getDataSourceMetrics
      deprecated: true
      parameters:
        - name: dataSourceName
          in: path
          description: dataSourceName
          required: true
          schema:
            type: string
        - name: interval
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSourceMetrics'
              example:
                $ref: /examples/get-data-source-metrics.json
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /druid/v2/datasources/{dataSourceName}/candidates:
    get:
      tags:
        - /router
      summary: getDataSourceCandidates
      operationId: getDataSourceCandidates
      deprecated: true
      parameters:
        - name: dataSourceName
          in: path
          description: dataSourceName
          required: true
          schema:
            type: string
        - name: interval
          in: query
          required: false
          schema:
            type: string
        - name: numCandidates
          in: query
          required: false
          schema:
            type: integer
            default: -1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSourceCandidates'
        401:
          description: Unauthorized
        403:
          description: Forbidden

components:
  schemas:
    ServerStatus:
      type: object
      properties:
        version:
          type: string
        modules:
          type: array
          items:
            $ref: '#/components/schemas/ModuleVersion'
        memory:
          $ref: '#/components/schemas/Memory'
    ModuleVersion:
      type: object
      properties:
        name:
          type: string
        artifact:
          type: string
        version:
          type: string
    Memory:
      type: object
      properties:
        maxMemory:
          type: integer
          format: int64
          example: 1073741824
        totalMemory:
          type: integer
          format: int64
          example: 1073741824
        freeMemory:
          type: integer
          format: int64
          example: 1016787424
        usedMemory:
          type: integer
          format: int64
          example: 56954400
        directMemory:
          type: integer
          format: int64
          example: 6471811072
    DataSource:
      type: object
      properties:
        dimensions:
          type: array
          items:
            type: string
        metrics:
          type: array
          items:
            type: string
    DataSourceDimention:
      type: array
      items:
        type: string
    DataSourceMetrics:
      type: array
      items:
        type: string
    DataSourceCandidates:
      type: array
      items:
        type: string

